### ISSUE TITLE
Carrington JAM successor?

### ISSUE THREAD

**Issue by emzo** [crowdfavorite/wp-carrington-blueprint#1]
Going forward, will Carrington Blueprint serve the same purpose as Carrington JAM once did, as a starter theme making use of Carrington Core? Is Carrington JAM now officially dead?

**Comment by alexkingorg** [comment]
We'll see how this comes along.

**Comment by emzo** [comment]
Just wondering why you decided to start work on another bare-bones Carrington starter theme when JAM already existed in that space? Just curious, that's all!

**Comment by enchance** [comment]
Is Carrington JAM still even alive? I love it and I've used it for several sites but the fact that it hasn't been updated in a long time scares me. That alone gives me reason to start shopping around.

**Comment by cfree** [comment]
@enchance Carrington JAM is no longer supported, however [Carrington Blueprint](https://github.com/crowdfavorite/wp-carrington-blueprint) is it's successor and is actively being maintained.
