### ISSUE TITLE
Remove CFCT_URL_VERSION

### ISSUE THREAD

**Issue by jaredkc** [crowdfavorite/wp-carrington-blueprint#10]
I propose we stop using the `CFCT_URL_VERSION` constant on all assets. No need to force reload every asset when only one has changed. Especially when it's a large multi-site setup with caching in place. Suggest replacing with a date string. 

This: 

```
wp_enqueue_script( 'modernizr', $cfct_assets_url . 'js/modernizr-2.8.2.min.js', array(), CFCT_URL_VERSION );
```

Becomes this: 

```
wp_enqueue_script( 'modernizr', $cfct_assets_url . 'js/modernizr-2.8.2.min.js', array(), '20141024' );
```

How does everyone feel about making this the default to start from here in carrington-blueprint?

**Comment by mospaw** [comment]
My only opposition to this would be that changing one constant in one place is easy (although it tends to get overlooked). Remembering to do it in a specific place in code (not at the top of a file) will get overlooked even more.

So which is the greater problem, occasionally re-caching some items even if they haven't changed, or not triggering caching of the new items via URL parameters?
