### ISSUE TITLE
Template/View retrieval logic of the Carrington Core Utility functions.

### ISSUE THREAD

**Issue by Lisa-Williams** [crowdfavorite/wp-carrington-blueprint#6]
Is the template/view retrieval logic of the [Carrington Core Utility functions](https://github.com/crowdfavorite/wp-carrington-core/blob/master/utility.php) similar (or even identical) to what is used in [X | The Theme](http://themeforest.net/item/x-the-theme/5871901)?

**Comment by cfree** [comment]
I'm assuming you tried to get information on Carrington Theme and were redirected to the X theme web site. The carringtontheme.com domain was sold a number of years ago and now currently forwards to this X theme, which is an unrelated project and unaffiliated with the makers of the Carrington suite, Crowd Favorite. 

We don't use the X theme and are unfamiliar with its template/view retrieval logic, but unless it uses the open source [Carrington Core theme engine](http://crowdfavorite.com/carrington-core/), it is unlikely that they are related.

**Comment by Lisa-Williams** [comment]
That's exactly what happened. Thanks for clearing that one up. :)

I was just wondering about the performance. Because for me the X Theme was pretty slow. And I checked at 3 different times of the day.
I'm going to test drive the Carrington Blueprint+Core this week. (If time permits.)
Thanks.

**Comment by Lisa-Williams** [comment]
On the page that you linked, I just read this:

> Carrington Core is not a platform for creating commercial WordPress themes, it is a framework for creating modular templates that are tied closely to the features of a specific website. 

So I'm passing up.
